const colors = {
  light: {
    text: "#111827",
    tint: "#FF8A00",
    background: "#F5F6FA",
    foreground: "#111827",
    card: "#FFFFFF",
    cardForeground: "#111827",
    primary: "#FF8A00",
    primaryForeground: "#FFFFFF",
    primaryLight: "#FF8A0018",
    primaryDark: "#FF5E00",
    secondary: "#6B7280",
    secondaryForeground: "#FFFFFF",
    accent: "#FF8A00",
    accentForeground: "#FFFFFF",
    muted: "#F1F5F9",
    mutedForeground: "#9CA3AF",
    border: "#E5E7EB",
    input: "#F8FAFC",
    surface: "#F1F5F9",
    surfaceElevated: "#FFFFFF",
    cyan: "#06B6D4",
    orange: "#FF8A00",
    green: "#10B981",
    purple: "#8B5CF6",
    yellow: "#F59E0B",
    red: "#EF4444",
    success: "#10B981",
    warning: "#F59E0B",
    error: "#EF4444",
    info: "#FF8A00",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
  },
  dark: {
    text: "#F9FAFB",
    tint: "#FF9A20",
    background: "#0F172A",
    foreground: "#F9FAFB",
    card: "#1E293B",
    cardForeground: "#F9FAFB",
    primary: "#FF9A20",
    primaryForeground: "#FFFFFF",
    primaryLight: "#FF9A2030",
    primaryDark: "#FF6E10",
    secondary: "#94A3B8",
    secondaryForeground: "#F9FAFB",
    accent: "#FF9A20",
    accentForeground: "#FFFFFF",
    muted: "#334155",
    mutedForeground: "#94A3B8",
    border: "#334155",
    input: "#1E293B",
    surface: "#0F172A",
    surfaceElevated: "#1E293B",
    cyan: "#06B6D4",
    orange: "#FF9A20",
    green: "#10B981",
    purple: "#8B5CF6",
    yellow: "#F59E0B",
    red: "#EF4444",
    success: "#10B981",
    warning: "#F59E0B",
    error: "#EF4444",
    info: "#FF9A20",
    destructive: "#F87171",
    destructiveForeground: "#FFFFFF",
  },
  radius: 22,
  radiusSmall: 12,
  radiusLarge: 30,
  radiusFull: 9999,
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 20,
    xl: 24,
    xxl: 32,
  },
  shadow: {
    soft: {
      shadowColor: "#FF8A00",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 2,
    },
    medium: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 4,
    },
    strong: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 20,
      elevation: 8,
    },
  },
  typography: {
    h1: { fontSize: 28, lineHeight: 36, fontFamily: "Inter_700Bold", letterSpacing: -0.5 },
    h2: { fontSize: 22, lineHeight: 30, fontFamily: "Inter_700Bold", letterSpacing: -0.3 },
    h3: { fontSize: 17, lineHeight: 24, fontFamily: "Inter_600SemiBold" },
    body: { fontSize: 15, lineHeight: 22, fontFamily: "Inter_400Regular" },
    bodyMedium: { fontSize: 15, lineHeight: 22, fontFamily: "Inter_500Medium" },
    caption: { fontSize: 13, lineHeight: 18, fontFamily: "Inter_400Regular" },
    label: { fontSize: 12, lineHeight: 16, fontFamily: "Inter_500Medium", letterSpacing: 0.5, textTransform: "uppercase" as const },
    tiny: { fontSize: 11, lineHeight: 14, fontFamily: "Inter_400Regular" },
  },
};

export type ColorTokens = typeof colors.light;
export type ThemeTokens = ColorTokens & {
  radius: typeof colors.radius;
  radiusSmall: typeof colors.radiusSmall;
  radiusLarge: typeof colors.radiusLarge;
  radiusFull: typeof colors.radiusFull;
  spacing: typeof colors.spacing;
  shadow: typeof colors.shadow;
  typography: typeof colors.typography;
};

export default colors;
